let dataBody = [
  {
    types: ".com",
    status: "Active",
    billing_date: "Annually",
    description: "Domain Web",
    price: "Rp200.000",
    discount: 10,
    promo_code: "NADFH65",
    title: "Promo Kemerdekaan",
  },
  {
    types: ".id",
    status: "Active",
    billing_date: "Annually",
    description: "Domain Web",
    price: "Rp200.000",
    discount: 10,
    promo_code: "NADFH65",
    title: "Promo Kemerdekaan",
  },
  {
    types: ".xyz",
    status: "Active",
    billing_date: "Annually",
    description: "Domain Web",
    price: "Rp200.000",
    discount: 10,
    promo_code: "NADFH65",
    title: "Promo Kemerdekaan",
  },
  {
    types: ".co.id",
    status: "Active",
    billing_date: "Annually",
    description: "Domain Web",
    price: "Rp200.000",
    discount: 10,
    promo_code: "NADFH65",
    title: "Promo Kemerdekaan",
  },
  {
    types: ".net",
    status: "Active",
    billing_date: "Annually",
    description: "Domain Web",
    price: "Rp200.000",
    discount: 10,
    promo_code: "NADFH65",
    title: "Promo Kemerdekaan",
  },
  {
    types: ".or.id",
    status: "Active",
    billing_date: "Annually",
    description: "Domain Web",
    price: "Rp200.000",
    discount: 10,
    promo_code: "NADFH65",
    title: "Promo Kemerdekaan",
  },
];

export default dataBody;
