const dataPesanan = [
  {
    name: "Indah Permata",
    email: "indah@gmail.com",
    no_telp: "+6281-2345-6789",
    url_template: "bwerokpa.com/asnfe/sldfasnd",
    plan: "Basic",
    domain: "ikrimah.xyy",
    billing_date: "March 31, 2023",
    billing_plan: "Monthly",
    description: "Domain Web",
    img_src: "../../../../src/assets/doc.png",
  },
  {
    name: "Cristhoper Jone",
    email: "cristhoper@gmail.com",
    no_telp: "+6281-2345-6789",
    url_template: "bwerokpa.com/asnfe/sldfasnd",
    plan: "Premium",
    domain: "ikrimah.xyy",
    billing_date: "March 31, 2023",
    billing_plan: "Monthly",
    description: "Domain Web",
    img_src: "../../../../src/assets/doc.png",
  },
  {
    name: "Aurel Natasya",
    email: "anatasya@gmail.com",
    no_telp: "+6281-2345-6789",
    url_template: "bwerokpa.com/asnfe/sldfasnd",
    plan: "Basic",
    domain: "ikrimah.xyy",
    billing_date: "March 31, 2023",
    billing_plan: "Monthly",
    description: "Domain Web",
    img_src: "../../../../src/assets/doc.png",
  },
  {
    name: "Rinda Sari",
    email: "sariirinda05@gmail.com",
    no_telp: "+6281-2345-6789",
    url_template: "bwerokpa.com/asnfe/sldfasnd",
    plan: "Premium",
    domain: "ikrimah.xyy",
    billing_date: "March 31, 2023",
    billing_plan: "Monthly",
    description: "Domain Web",
    img_src: "../../../../src/assets/doc.png",
  },
  {
    name: "Philjones",
    email: "jones@gmail.com",
    no_telp: "+6281-2345-6789",
    url_template: "bwerokpa.com/asnfe/sldfasnd",
    plan: "Basic",
    domain: "ikrimah.xyy",
    billing_date: "March 31, 2023",
    billing_plan: "Monthly",
    description: "Domain Web",
    img_src: "../../../../src/assets/doc.png",
  },
  {
    name: "Chelsea",
    email: "chelsea@gmail.com",
    no_telp: "+6281-2345-6789",
    url_template: "bwerokpa.com/asnfe/sldfasnd",
    plan: "Basic",
    domain: "ikrimah.xyy",
    billing_date: "March 31, 2023",
    billing_plan: "Monthly",
    description: "Domain Web",
    img_src: "../../../../src/assets/doc.png",
  },
  {
    name: "Silvio Morreira",
    email: "silvio@gmail.com",
    no_telp: "+6281-2345-6789",
    url_template: "bwerokpa.com/asnfe/sldfasnd",
    plan: "Basic",
    domain: "ikrimah.xyy",
    billing_date: "March 31, 2023",
    billing_plan: "Monthly",
    description: "Domain Web",
    img_src: "../../../../src/assets/doc.png",
  },
  {
    name: "Bernando Silva",
    email: "Bernando@gmail.com",
    no_telp: "+6281-2345-6789",
    url_template: "bwerokpa.com/asnfe/sldfasnd",
    plan: "Basic",
    domain: "ikrimah.xyy",
    billing_date: "March 31, 2023",
    billing_plan: "Monthly",
    description: "Domain Web",
    img_src: "../../../../src/assets/doc.png",
  },
];

export default dataPesanan;
