let dataDetail = [
  {
    packet: "Premium",
    status: "Active",
    name: "Leslie Alexander",
    fitur: "Responsive Website",
    price: "Rp200.000",
    time: "1 Tahun",
    company: "PT. Jaya Mandiri",
  },
  {
    packet: "Basic",
    status: "Active",
    name: "Leslie Alexander",
    fitur: "Responsive Website",
    price: "Rp200.000",
    time: "1 Tahun",
    company: "PT. Jaya Mandiri",
  },
  {
    packet: "Premium",
    status: "Active",
    name: "Leslie Alexander",
    fitur: "Responsive Website",
    price: "Rp200.000",
    time: "1 Tahun",
    company: "PT. Jaya Mandiri",
  },
  {
    packet: "Basic",
    status: "Active",
    name: "Leslie Alexander",
    fitur: "Responsive Website",
    price: "Rp200.000",
    time: "1 Tahun",
    company: "PT. Jaya Mandiri",
  },
  {
    packet: "Premium",
    status: "Active",
    name: "Leslie Alexander",
    fitur: "Responsive Website",
    price: "Rp200.000",
    time: "1 Tahun",
    company: "PT. Jaya Mandiri",
  },
  {
    packet: "Basic",
    status: "Active",
    name: "Leslie Alexander",
    fitur: "Responsive Website",
    price: "Rp200.000",
    time: "1 Tahun",
    company: "PT. Jaya Mandiri",
  },
  {
    packet: "Premium",
    status: "Active",
    name: "Leslie Alexander",
    fitur: "Responsive Website",
    price: "Rp200.000",
    time: "1 Tahun",
    company: "PT. Jaya Mandiri",
  },
  {
    packet: "Basic",
    status: "Active",
    name: "Leslie Alexander",
    fitur: "Responsive Website",
    price: "Rp200.000",
    time: "1 Tahun",
    company: "PT. Jaya Mandiri",
  },
  {
    packet: "Premium",
    status: "Active",
    name: "Leslie Alexander",
    fitur: "Responsive Website",
    price: "Rp200.000",
    time: "1 Tahun",
    company: "PT. Jaya Mandiri",
  },
];

export default dataDetail;
