let dataBody = [
  {
    project: "New Game 23",
    category: "Website",
    releases_date: "2023/03/23",
    status: "Publish",
    description: "lorem ippsum..",
    tools: "figma",
    language: "indonesia",
    link: "",
  },
  {
    project: "New Game 23",
    category: "Website",
    releases_date: "2023/03/23",
    status: "Unpublish",
    description: "lorem ippsum..",
    tools: "figma",
    language: "indonesia",
    link: "",
  },
  {
    project: "New Game 23",
    category: "Website",
    releases_date: "2023/03/23",
    status: "Publish",
    description: "lorem ippsum..",
    tools: "figma",
    language: "indonesia",
    link: "",
  },
  {
    project: "New Game 23",
    category: "Website",
    releases_date: "2023/03/23",
    status: "Unpublish",
    description: "lorem ippsum..",
    tools: "figma",
    language: "indonesia",
    link: "",
  },
  {
    project: "New Game 23",
    category: "Website",
    releases_date: "2023/03/23",
    status: "Publish",
    description: "lorem ippsum..",
    tools: "figma",
    language: "indonesia",
    link: "",
  },
  {
    project: "New Game 23",
    category: "Website",
    releases_date: "2023/03/23",
    status: "Unpublish",
    description: "lorem ippsum..",
    tools: "figma",
    language: "indonesia",
    link: "",
  },
  {
    project: "New Game 23",
    category: "Website",
    releases_date: "2023/03/23",
    status: "Publish",
    description: "lorem ippsum..",
    tools: "figma",
    language: "indonesia",
    link: "",
  },
  {
    project: "New Game 23",
    category: "Website",
    releases_date: "2023/03/23",
    status: "Unpublish",
    description: "lorem ippsum..",
    tools: "figma",
    language: "indonesia",
    link: "",
  },
];

export default dataBody;
